# This file was generated by GoReleaser. DO NOT EDIT.
cask "cq" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/mozilla-ai/cq/releases/download/v#{version}/cq_Darwin_x86_64.tar.gz"
      sha256 "12012404975f05dd134a959ce2f2b990430f1cf9e48413f2801026177be10b5e"
    end
    on_arm do
      url "https://github.com/mozilla-ai/cq/releases/download/v#{version}/cq_Darwin_arm64.tar.gz"
      sha256 "a3edb00f376476d68e3fc1e42df08420ee7ca7947017d33df6dfa716f6b5a68d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mozilla-ai/cq/releases/download/v#{version}/cq_Linux_x86_64.tar.gz"
      sha256 "ab6f9f7481dc4a67fa57eb117041d951132f236765ed2a84e36d7857f16c474a"
    end
    on_arm do
      url "https://github.com/mozilla-ai/cq/releases/download/v#{version}/cq_Linux_arm64.tar.gz"
      sha256 "574a159bdc77c437fced56fe541fb62aab4ecc098f9744a913ce2a6834d6c0cd"
    end
  end

  name "cq"
  desc "cq is a shared knowledge store that helps agents avoid known pitfalls.
"
  homepage "https://github.com/mozilla-ai/cq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cq"]
    end
  end

  # No zap stanza required

end
