# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpd" do
  name "mcpd"
  desc "A tool to declaratively manage Model Context Protocol (MCP) servers, providing a consistent interface to define and run tools across environments, from local development to containerized cloud deployments.
"
  homepage "https://github.com/mozilla-ai/mcpd"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpd"

  on_macos do
    on_intel do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Darwin_x86_64.tar.gz"
      sha256 "82b8d6f5eb7ffcc00b40d6e75cf83d490298dd04ebc89cbfd4273cd6ea4b3b7f"
    end
    on_arm do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Darwin_arm64.tar.gz"
      sha256 "02b28283b7d7ef7c5fe0992f4aee4c67dc05c524cd8fe28a004b90ebf0cdec26"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Linux_x86_64.tar.gz"
      sha256 "8a0089dbcc61fc64b92869ae8b4784a9dae538f64db0c0dcc7f053defce72759"
    end
    on_arm do
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Linux_arm64.tar.gz"
      sha256 "505b308d0c96d4d3ae5d1930db0e965ae2c904b27104defd3783b7c28322bf08"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpd"]
    end
  end

  # No zap stanza required
end
