# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpd" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "b1fbb8fc40a789e866c24c92e81926cb0a7f86f6f2028c35a9ff255f4df2b324"
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2341fa7d7ae01b22a2ba42aa37d77d38f0b67379505e641c3ed5627a8a9c6b6a"
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "75390884e8c8292b0d16e8820edd1b3cc32605f33d97a692a78a37c38902f5f6"
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e93b63ca7ef71dca1eaeb853a36dd199d3e78d793ede0e42e5c7fae693aeb0bf"
      url "https://github.com/mozilla-ai/mcpd/releases/download/v#{version}/mcpd_Linux_arm64.tar.gz"
    end
  end

  name "mcpd"
  desc "A tool to declaratively manage Model Context Protocol (MCP) servers, providing a consistent interface to define and run tools across environments, from local development to containerized cloud deployments.
"
  homepage "https://github.com/mozilla-ai/mcpd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpd"]
    end
  end

  # No zap stanza required

end
